// Import necessary modules
const express = require('express');
const { MongoClient, ObjectId } = require('mongodb');
const path = require('path');

// Initialize Express app
const app = express();
const port = process.env.PORT || 3000;

// Serve static files from the "public" directory
app.use(express.static(path.join(__dirname, 'public')));

// MongoDB connection URI
const mongoURI = 'mongodb+srv://ElijahLegacy:bGp3MuIXzjmEvwtA@webstore.jgfc71s.mongodb.net/';

// MongoDB collections
let ordersCollection;
let lessonsCollection;

// Connect to MongoDB
async function connectToMongo() {
    const client = new MongoClient(mongoURI);
    try {
        await client.connect();
        console.log('Connected to MongoDB');
        
        const db = client.db('MongoCLoud');
        ordersCollection = db.collection('orders');
        lessonsCollection = db.collection('lessons');

        // Start the server
        app.listen(port, () => {
            console.log(`Server is running on port ${port}`);
        });
    } catch (error) {
        console.error('Error connecting to MongoDB:', error);
    }
}

// Middleware to log requests
app.use((req, res, next) => {
    console.log(`${req.method} ${req.url}`);
    next();
});

// Call the function to connect to MongoDB
connectToMongo();

// Define GET route to fetch all lessons
app.get('/lessons', (req, res) => {
    lessonsCollection.find({}).toArray()
        .then(lessons => {
            res.status(200).json(lessons);
        })
        .catch(err => {
            console.error('Error fetching lessons:', err);
            res.status(500).json({ error: 'An error occurred while fetching lessons' });
        });
});

// Define GET route to fetch a specific lesson by ID
app.get('/lessons/:id', (req, res) => {
    const lessonId = req.params.id;
    try {
        const objectId = new ObjectId(lessonId);
        lessonsCollection.findOne({ _id: objectId })
            .then(lesson => {
                if (!lesson) {
                    return res.status(404).json({ error: 'Lesson not found' });
                }
                res.status(200).json(lesson);
            })
            .catch(err => {
                console.error('Error fetching lesson:', err);
                res.status(500).json({ error: 'An error occurred while fetching the lesson' });
            });
    } catch (error) {
        console.error('Invalid lesson ID:', error);
        res.status(400).json({ error: 'Invalid lesson ID' });
    }
});

// Define POST route to place orders
app.post('/orders', (req, res) => {
    const orderData = req.body; // Get order data from request body
    
    // Validate that orderData is not null or undefined
    if (!orderData) {
        return res.status(400).json({ error: 'Order data is missing or invalid' });
    }

    // Remove _id field from orderData if it's not needed or generated by MongoDB
    delete orderData._id; // This assumes MongoDB generates _id automatically

    // Validate that orderData contains lessonIds property
    if (!orderData.lessonIds || !Array.isArray(orderData.lessonIds)) {
        return res.status(400).json({ error: 'Lesson IDs are missing or invalid' });
    }

    ordersCollection.insertOne(orderData)
        .then(result => {
            console.log('Order placed:', result.ops[0]);
            // Call function to update lesson inventory
            updateLessonInventory(orderData.lessonIds);
            res.status(201).json({ message: 'Order placed successfully' });
        })
        .catch(err => {
            console.error('Error placing order:', err);
            res.status(500).json({ error: 'An error occurred while placing the order' });
        });
});





// Define PUT route to update available lesson spaces
app.put('/lessons/:id/update-space', (req, res) => {
    const lessonId = req.params.id;
    const newSpace = req.body.newSpace;

    lessonsCollection.updateOne({ _id: ObjectId(lessonId) }, { $set: { space: newSpace } })
        .then(result => {
            res.status(200).json({ message: 'Lesson space updated successfully' });
        })
        .catch(err => {
            console.error('Error updating lesson space:', err);
            res.status(500).json({ error: 'An error occurred while updating lesson space' });
        });
});

// Function to update lesson inventory
function updateLessonInventory(lessonIds) {
    lessonIds.forEach(lessonId => {
        const lessonIdInt = parseInt(lessonId);
        const lessonUpdate = { $inc: { availableInventory: -1 } }; // Decrease available inventory by 1
        lessonsCollection.updateOne({ _id: lessonIdInt }, lessonUpdate)
            .then(result => {
                console.log(`Inventory updated for lesson with ID ${lessonId}`);
            })
            .catch(err => {
                console.error(`Error updating inventory for lesson with ID ${lessonId}:`, err);
            });
    });
}

// Handle errors
app.use((err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: 'Internal Server Error' });
});
